#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.75.1.

use crate::apis::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_return_trips_impl(port_: MessagePort, json: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "return_trips",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_json = json.wire2api();
            move |task_callback| return_trips(api_json)
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for DropOffPoint {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.status.into_dart(),
            self.capacity.into_dart(),
            self.gas_type.into_dart(),
            self.time_stamp.into_dart(),
            self.location_name.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for DropOffPoint {}

impl support::IntoDart for StepCompleteTime {
    fn into_dart(self) -> support::DartAbi {
        vec![self.terminal.into_dart(), self.drop_off_points.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for StepCompleteTime {}

impl support::IntoDart for StepCompleteTimeDB {
    fn into_dart(self) -> support::DartAbi {
        vec![self.terminal.into_dart(), self.drop_off_points.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for StepCompleteTimeDB {}

impl support::IntoDart for Terminal {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.time_stamp.into_dart(),
            self.terminal_name.into_dart(),
            self.status.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Terminal {}

impl support::IntoDart for Trip {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.ID.into_dart(),
            self.CreatedAt.into_dart(),
            self.UpdatedAt.into_dart(),
            self.DeletedAt.into_dart(),
            self.car_id.into_dart(),
            self.driver_id.into_dart(),
            self.car_no_plate.into_dart(),
            self.driver_name.into_dart(),
            self.transporter.into_dart(),
            self.tank_capacity.into_dart(),
            self.pick_up_point.into_dart(),
            self.progress_index.into_dart(),
            self.step_complete_time.into_dart(),
            self.step_complete_time_db.into_dart(),
            self.no_of_drop_off_points.into_dart(),
            self.date.into_dart(),
            self.fee_rate.into_dart(),
            self.mileage.into_dart(),
            self.start_time.into_dart(),
            self.end_time.into_dart(),
            self.is_closed.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Trip {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
